### ISSUE TITLE
SW 5.6 and dump: Argument 1 passed to Symfony\Component\VarDumper\Dumper\AbstractDumper::dump() must be an instance of Symfony\Component\VarDumper\Cloner\Data

### ISSUE THREAD

**Issue by rofthedeep** [FriendsOfShopware/FroshProfiler#109]
Hi :)

today I tried Shopware 5.6 and updated the Profiler, too.

With using `dump('test');` in my code I'm getting the following error:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\VarDumper\Dumper\AbstractDumper::dump() must be an instance of Symfony\Component\VarDumper\Cloner\Data, string given, called in /var/www/html/custom/plugins/FroshProfiler/vendor/symfony/var-dumper/Command/Descriptor/CliDescriptor.php on line 55 and defined in /var/www/html/custom/plugins/FroshProfiler/vendor/symfony/var-dumper/Dumper/AbstractDumper.php:124
Stack trace:
#0 /var/www/html/custom/plugins/FroshProfiler/vendor/symfony/var-dumper/Command/Descriptor/CliDescriptor.php(55): Symfony\Component\VarDumper\Dumper\AbstractDumper->dump('listing', true)
#1 /var/www/html/custom/plugins/FroshProfiler/vendor/symfony/var-dumper/Command/ServerDumpCommand.php(96): Symfony\Component\VarDumper\Command\Descriptor\CliDescriptor->describe(Object(Symfony\Component\Console\Style\SymfonyStyle), Object(Symfony\Component\VarDumper\Cloner\Data), Array, 475)
#2 /var/www/html/custom/plugins/FroshProfiler/vendor/symfony/var-dumper/Server/DumpServer.php(76): Symfony\Compon in /var/www/html/custom/plugins/FroshProfiler/vendor/symfony/var-dumper/Dumper/AbstractDumper.php on line 124

Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\VarDumper\Dumper\AbstractDumper::dump() must be an instance of Symfony\Component\VarDumper\Cloner\Data, string given, called in /var/www/html/custom/plugins/FroshProfiler/vendor/symfony/var-dumper/Command/Descriptor/CliDescriptor.php on line 55 and defined in /var/www/html/custom/plugins/FroshProfiler/vendor/symfony/var-dumper/Dumper/AbstractDumper.php:124
Stack trace:
#0 /var/www/html/custom/plugins/FroshProfiler/vendor/symfony/var-dumper/Command/Descriptor/CliDescriptor.php(55): Symfony\Component\VarDumper\Dumper\AbstractDumper->dump('listing', true)
#1 /var/www/html/custom/plugins/FroshProfiler/vendor/symfony/var-dumper/Command/ServerDumpCommand.php(96): Symfony\Component\VarDumper\Command\Descriptor\CliDescriptor->describe(Object(Symfony\Component\Console\Style\SymfonyStyle), Object(Symfony\Component\VarDumper\Cloner\Data), Array, 475)
#2 /var/www/html/custom/plugins/FroshProfiler/vendor/symfony/var-dumper/Server/DumpServer.php(76): Symfony\Compon in /var/www/html/custom/plugins/FroshProfiler/vendor/symfony/var-dumper/Dumper/AbstractDumper.php on line 124
make: *** [dump] Error 255
```

I've started the profiler with the following command: `php bin/console server:dump`

![Bildschirmfoto 2019-08-19 um 14 16 10](https://user-images.githubusercontent.com/2420176/63264657-e9302500-c28b-11e9-9288-d06073eb812e.png)

![Bildschirmfoto 2019-08-19 um 14 16 39](https://user-images.githubusercontent.com/2420176/63264687-fb11c800-c28b-11e9-9516-6d02dc41769e.png)

Perhaps you've got an idea where this issue comes from?

Best,
Tim

**Comment by alandolsi** [comment]
I have the same problem, do you have a solution?

**Comment by shyim** [comment]
Are you using the latest version?

**Comment by alandolsi** [comment]
yes and it worked yesterday already

**Comment by shyim** [comment]
Can you create a new issue with a description how to reproduce this?

**Comment by alandolsi** [comment]
ok
